# Archivo para calcular rentabilidad de un portafolio

In [2]:
##### Modulos necesarios
import pandas as pd
import numpy as np
from tqdm import tqdm

# Rentabilidad equilibrada

Por varias razones, una rentabilidad equilibrada es necesaria para medir diferences mas equitativamente. La formula es

$R_t = \sum_i^n \frac{\sigma_{tgt}}{\tilde{\sigma}_{i,t-1}} * w_{i,t-1} * r_{i,t} - C*\sum_i^n | \frac{\sigma_{tgt}}{\tilde{\sigma}_{i,t-1}} * w_{i,t-1} - \frac{\sigma_{tgt}}{\tilde{\sigma}_{i,t-2}} * w_{i,t-2} |$

Los requisitos para calcular esta rentabilidad son:
- Rendimientos: $r_{i,t}$
- Pesas del portafolio: $w_{i,t}$
- Exponentially Weighted Moving Standar Deviation (EWMSD): $\tilde{\sigma}_{i,t-1}$
- Constantes - volatilidad deseada $\sigma_{tgt}$ y costo de transacciones $C$

El EWMA generalmente se calcula en la siguiente manera:

$\text{EWMA}_t(x) = \alpha * x_t + (1-\alpha) * \text{EWMA}_{t-1}(x)$

Implicando que el EWMSD es:

$\tilde{\sigma}_{i,t} = \sqrt{\alpha(r_t-\mu_{t-1})^2 + (1-\alpha)\tilde{\sigma}_{t-1}^2}$

In [ ]:
##### Creando datos necesarios
#### Rendimientos
df_rendis = pd.read_csv('retornos.csv', index_col='Date')

#### Nombre de las 32 empresas
empresas = df_rendis.columns.to_list()

#### Calculando EWMSD
for name in empresas:
    df_rendis[f'EWMSD.{name}'] = df_rendis[name].ewm(span=30, adjust=False).std()
    # df_rendis[f'Posicion.{name}'] = [1] * df_rendis.shape[0]  #Posiciones falsas
    # df_rendis[f'Rentabilidad.{name}'] = df_rendis[name] * (1/df_rendis[f'EWMSD.{name}'].shift(1))  *df_rendis[f'Posicion.{name}'].shift(1) - \
    # 1*abs(((1/df_rendis[f'EWMSD.{name}'].shift(1))*df_rendis[f'Posicion.{name}'].shift(1)) - ((1/df_rendis[f'EWMSD.{name}'].shift(2))*df_rendis[f'Posicion.{name}'].shift(2)))
    #     #Simulando rentabilidad calculacion

Date
2006-02-28    0.000000
2006-03-01    0.000000
2006-03-02    0.139047
2006-03-03   -0.011426
2006-03-06   -0.576579
                ...
2026-06-08   -0.131398
2026-06-09    0.306557
2026-06-10   -0.089044
2026-06-11    1.116965
2026-06-12    0.332852
Length: 5291, dtype: float64

In [ ]:
##### DEBUG ---- Creando datos necesarios
#### Rendimientos
df_rendis = pd.read_csv('retornos.csv', index_col='Date')

empresas = df_rendis.columns.to_list()
print(empresas)
sums = df_rendis.sum(axis=1)
display(sums)

#### EWMSD
# df = pd.DataFrame({'valor': [10, 20, 15, 25, 30]})
# resultado = df.ewm(span=30, adjust=False).std()

for name in df_rendis.columns:
    # df_rendis[f'EWMSD.{name}'] = df_rendis[name].ewm(span=30, adjust=False).std()   # Verdadero
    df_rendis[f'EWMSD.{name}']  = [1] * df_rendis.shape[0]  #Debug
    df_rendis[f'Posicion.{name}'] = [1] * df_rendis.shape[0]  #Debug

# display(df_rendis.head())

#Form 1
form1 = pd.DataFrame(index=df_rendis.index)
# for name in empresas:
#     form1[name] = df_rendis[name]*df_rendis[f'Posicion.{name}'].shift(2)

# display(form1.sum(axis=1))

# Form 2
# for name in empresas:
#     form1[name] = df_rendis[name] * (0.1/df_rendis[f'EWMSD.{name}'].shift(3))  *df_rendis[f'Posicion.{name}'].shift(2)


# display(form1.sum(axis=1))


# Form 4
for name in empresas:
    form1[name] = df_rendis[name] * (1/df_rendis[f'EWMSD.{name}'].shift(1))  *df_rendis[f'Posicion.{name}'].shift(1) - \
    1*abs(((1/df_rendis[f'EWMSD.{name}'].shift(1))*df_rendis[f'Posicion.{name}'].shift(1)) - ((1/df_rendis[f'EWMSD.{name}'].shift(2))*df_rendis[f'Posicion.{name}'].shift(2)))

display(form1.sum(axis=1))

['ABEV', 'AC', 'AMXB', 'AXIA3', 'BAP', 'BBAS3', 'BBD', 'BIMBOA', 'BSAC', 'CEMEXCPO', 'CENCOSUD', 'CIB', 'FALABELLA', 'FEMSAUBD', 'GCARSOA1', 'GFNORTEO', 'GGB', 'GMEXICOB', 'ISA', 'ITSA4', 'ITUB', 'PAC', 'PBR', 'PBR-A', 'RENT3', 'SBSP3', 'SCCO', 'SQM', 'VALE', 'VIV', 'WALMEX', 'WEGE3']

Date
2006-02-28   -0.153850
2006-03-01    0.713369
2006-03-02    0.139047
2006-03-03   -0.011426
2006-03-06   -0.576579
                ...
2026-06-08   -0.131398
2026-06-09    0.306557
2026-06-10   -0.089044
2026-06-11    1.116965
2026-06-12    0.332852
Length: 5291, dtype: float64

Date
2006-02-28    0.000000
2006-03-01    0.000000
2006-03-02    0.139047
2006-03-03   -0.011426
2006-03-06   -0.576579
                ...
2026-06-08   -0.131398
2026-06-09    0.306557
2026-06-10   -0.089044
2026-06-11    1.116965
2026-06-12    0.332852
Length: 5291, dtype: float64

In [50]:
##### Expeimrentos
tgt = 10
# df = pd.Series([10, 20, 30, 40, 50])
df = pd.DataFrame({'valor': [10, 20, 15, 25, 30], 'val':[-1,-2,-3,-4,-5]})
df3 = pd.DataFrame({'valor': [10, 20, 15, 25, 30]})
df2 = pd.DataFrame({'valor': [10, 20, 15, 25, 30]})
df4 = pd.DataFrame({'valor': [-1,-2,-3]})
print(abs(df4['valor']))
res = df3 * df2
display(res)
display(10/df2.shift(1))

0    1
1    2
2    3
Name: valor, dtype: int64

   valor
0    100
1    400
2    225
3    625
4    900

      valor
0       NaN
1  1.000000
2  0.500000
3  0.666667
4  0.400000